name: demo_VR

root: 'C:/Users/nokai/Documents/GitHub/Asovi_VR/'

export: 'camera_test/'
export_name: 'YMH_100'


model:
 yolo_detection: False
 yolo_model_path: './config/yolov5s.pt'
 Trigger: False

capture_style:
 stream_MSS: False


trigger:
 trigger_threshold_configuration: 0.5
 trigger_class: 'person'
 Arduino_COM: 'None'
 trigger_style: "projecter_drawing"
 
hardware:
 use_camera: True
 camera_id: 1
 camera_width: 1280
 camera_height: 1024
 camera_scale: 1
 camera_fps: 30
 camera_imshow: False # opencv-window

